"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-24 12:19:14.805618
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Autogenerated from interior_ai.db.models -- kept in sync with schema.sql.
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_observed_at'), 'price_history', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_history_sku'), 'price_history', ['sku'], unique=False)
    op.create_index('ix_price_history_sku_observed', 'price_history', ['sku', 'observed_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_current',
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_current_non_negative'),
    sa.ForeignKeyConstraint(['history_id'], ['price_history.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('scene_versions',
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('parent_version_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_scene_version_positive'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['scene_versions.version_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('scene_id', 'version', name='uq_scene_version')
    )
    op.create_index(op.f('ix_scene_versions_created_at'), 'scene_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_scene_versions_scene_id'), 'scene_versions', ['scene_id'], unique=False)
    op.create_index('ix_scene_versions_scene_version', 'scene_versions', ['scene_id', 'version'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('scene_version_id', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stale_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_complete', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_version_id'], ['scene_versions.version_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_generated_at'), 'quotes', ['generated_at'], unique=False)
    op.create_index(op.f('ix_quotes_scene_id'), 'quotes', ['scene_id'], unique=False)
    op.create_table('quote_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=True),
    sa.Column('price_status', sa.String(length=16), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_age_days', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_quantity_non_negative'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_lines_quote', 'quote_lines', ['quote_id'], unique=False)
    


def downgrade() -> None:
    # Autogenerated from interior_ai.db.models -- kept in sync with schema.sql.
    op.drop_index('ix_quote_lines_quote', table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index(op.f('ix_quotes_scene_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_generated_at'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_scene_versions_scene_version', table_name='scene_versions')
    op.drop_index(op.f('ix_scene_versions_scene_id'), table_name='scene_versions')
    op.drop_index(op.f('ix_scene_versions_created_at'), table_name='scene_versions')
    op.drop_table('scene_versions')
    op.drop_table('price_current')
    op.drop_table('projects')
    op.drop_index('ix_price_history_sku_observed', table_name='price_history')
    op.drop_index(op.f('ix_price_history_sku'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_observed_at'), table_name='price_history')
    op.drop_table('price_history')
    
